### ISSUE TITLE
Issue during Installation - openant dependency issue

### ISSUE THREAD

**Issue by kkarnasHD** [jludwig75/trainer_tools#29]
Hello,

The installation process includes a dependency on the "openant" package, and it seems there is an error related to the absence of the setup.py file in the "openant" repository. As a result, the installation script fails

Logs:
---------
2024-02-01 23:40:09,263 - root - INFO -   Installing "openant"...
Cloning into 'openant'...
remote: Enumerating objects: 1643, done.
remote: Counting objects: 100% (223/223), done.
remote: Compressing objects: 100% (105/105), done.
remote: Total 1643 (delta 138), reused 158 (delta 114), pack-reused 1420
Receiving objects: 100% (1643/1643), 391.18 KiB | 755.00 KiB/s, done.
Resolving deltas: 100% (1074/1074), done.
python3: can't open file '/home/kk/trainer_tools/openant/setup.py': [Errno 2] No such file or directory
2024-02-01 23:40:13,562 - root - INFO -   checking to see if "pyusb" is installed
2024-02-01 23:40:13,565 - root - INFO -   checking to see if "pip3" is installed
2024-02-01 23:40:13,593 - root - INFO -   package "pip3" is already installed
2024-02-01 23:40:13,597 - root - INFO -   package "pyusb" is already installed
Traceback (most recent call last):
  File "/home/kk/trainer_tools/./setup.py", line 9, in <module>
    pkg.install()
  File "/home/kk/trainer_tools/setup/trainertools.py", line 27, in install
    self._do_system_install()
  File "/home/kk/trainer_tools/setup/trainertools.py", line 34, in _do_system_install
    super().install_dependencies()
  File "/home/kk/trainer_tools/setup/package.py", line 35, in install_dependencies
    raise Exception('Failed to install package "%s"' % package.name)
Exception: Failed to install package "openant"
---------

Thank you in advance!

**Comment by kkarnasHD** [comment]
In file trainer_tools/setup/packages.py you need to change clone to clone --branch tag, because in master there is no file like setup.py
